-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/atan_simulink/gcordicAtan_pkg.vhd
-- Created: 2018-12-12 14:51:42
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE gcordicAtan_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END gcordicAtan_pkg;

