-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/atan_simulink/gcordicAtan.vhd
-- Created: 2018-12-12 14:51:42
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: gcordicAtan
-- Source Path: atan_simulink/gcordicAtan
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.gcordicAtan_pkg.ALL;

ENTITY gcordicAtan IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En13
        In2                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En13
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En13
        );
END gcordicAtan;


ARCHITECTURE rtl OF gcordicAtan IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL In1_signed                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay2_reg                  : vector_of_signed16(0 TO 1);  -- sfix16 [2]
  SIGNAL Unit_Delay2_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Compare_To_Zero_out1             : std_logic;
  SIGNAL In2_signed                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay3_reg                  : vector_of_signed16(0 TO 1);  -- sfix16 [2]
  SIGNAL Unit_Delay3_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Compare_To_Zero1_out1            : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL Delay2_reg                       : std_logic_vector(0 TO 11);  -- ufix1 [12]
  SIGNAL Delay2_out1                      : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Compare_To_Zero2_out1            : std_logic;
  SIGNAL Delay1_reg                       : std_logic_vector(0 TO 10);  -- ufix1 [11]
  SIGNAL Delay1_out1                      : std_logic;
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL Compare_To_Zero3_out1            : std_logic;
  SIGNAL switch_compare_1_2               : std_logic;
  SIGNAL Constant15_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL minusina_sub_cast                : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL minusina_sub_cast_1              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL minusina_sub_temp                : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL minusina_out1                    : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL plusina_sub_cast                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL plusina_sub_cast_1               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL plusina_sub_temp                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL plusina_out1                     : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempB_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay5_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Constant23_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Relational_Operator1_relop1      : std_logic;
  SIGNAL switch_compare_1_3               : std_logic;
  SIGNAL switch_compare_1_4               : std_logic;
  SIGNAL plusinb_sub_cast                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL plusinb_sub_cast_1               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL plusinb_sub_temp                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL plusinb_out1                     : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL minusinb_sub_cast                : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL minusinb_sub_cast_1              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL minusinb_sub_temp                : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL minusinb_out1                    : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempA_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay4_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract3_sub_cast               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract3_sub_cast_1             : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract3_sub_temp               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract3_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add1_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add1_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add1_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add1_out1                        : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempB1_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay8_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Relational_Operator2_relop1      : std_logic;
  SIGNAL switch_compare_1_5               : std_logic;
  SIGNAL switch_compare_1_6               : std_logic;
  SIGNAL Add2_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add2_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add2_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add2_out1                        : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract4_sub_cast               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract4_sub_cast_1             : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract4_sub_temp               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract4_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempA1_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay7_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Bit_Shift2_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract6_sub_cast               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract6_sub_cast_1             : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract6_sub_temp               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract6_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add4_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add4_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add4_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add4_out1                        : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempB2_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay11_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Relational_Operator3_relop1      : std_logic;
  SIGNAL switch_compare_1_7               : std_logic;
  SIGNAL switch_compare_1_8               : std_logic;
  SIGNAL Bit_Shift3_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add5_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add5_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add5_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add5_out1                        : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract7_sub_cast               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract7_sub_cast_1             : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract7_sub_temp               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract7_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempA2_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay12_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Bit_Shift4_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract9_sub_cast               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract9_sub_cast_1             : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract9_sub_temp               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract9_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add7_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add7_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add7_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add7_out1                        : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempB3_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay14_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Relational_Operator4_relop1      : std_logic;
  SIGNAL switch_compare_1_9               : std_logic;
  SIGNAL switch_compare_1_10              : std_logic;
  SIGNAL Bit_Shift5_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add8_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add8_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add8_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add8_out1                        : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract10_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract10_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract10_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract10_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempA3_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay15_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Bit_Shift6_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract12_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract12_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract12_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract12_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add10_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add10_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add10_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add10_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempB4_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay17_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Relational_Operator5_relop1      : std_logic;
  SIGNAL switch_compare_1_11              : std_logic;
  SIGNAL switch_compare_1_12              : std_logic;
  SIGNAL Bit_Shift7_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add11_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add11_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add11_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add11_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract13_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract13_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract13_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract13_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempA4_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay18_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Bit_Shift8_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract15_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract15_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract15_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract15_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add13_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add13_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add13_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add13_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempB5_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay20_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Relational_Operator6_relop1      : std_logic;
  SIGNAL switch_compare_1_13              : std_logic;
  SIGNAL switch_compare_1_14              : std_logic;
  SIGNAL Bit_Shift9_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add14_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add14_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add14_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add14_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract16_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract16_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract16_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract16_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempA5_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay21_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Bit_Shift10_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract18_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract18_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract18_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract18_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add16_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add16_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add16_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add16_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempB6_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay23_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Relational_Operator7_relop1      : std_logic;
  SIGNAL switch_compare_1_15              : std_logic;
  SIGNAL switch_compare_1_16              : std_logic;
  SIGNAL Bit_Shift11_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add17_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add17_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add17_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add17_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract19_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract19_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract19_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract19_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempA6_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay24_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Bit_Shift12_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract21_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract21_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract21_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract21_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add19_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add19_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add19_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add19_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempB7_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay26_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Relational_Operator8_relop1      : std_logic;
  SIGNAL switch_compare_1_17              : std_logic;
  SIGNAL switch_compare_1_18              : std_logic;
  SIGNAL Bit_Shift13_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add20_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add20_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add20_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add20_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract22_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract22_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract22_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract22_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempA7_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay25_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Bit_Shift14_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract24_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract24_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract24_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract24_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add22_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add22_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add22_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add22_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempB8_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay29_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Relational_Operator9_relop1      : std_logic;
  SIGNAL switch_compare_1_19              : std_logic;
  SIGNAL switch_compare_1_20              : std_logic;
  SIGNAL Bit_Shift15_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add23_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add23_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add23_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add23_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract25_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract25_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract25_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract25_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempA8_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay30_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Bit_Shift16_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract27_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract27_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract27_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract27_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add25_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add25_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add25_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add25_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL tempB9_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay32_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Relational_Operator10_relop1     : std_logic;
  SIGNAL switch_compare_1_21              : std_logic;
  SIGNAL switch_compare_1_22              : std_logic;
  SIGNAL switch_compare_1_23              : std_logic;
  SIGNAL switch_compare_1_24              : std_logic;
  SIGNAL switch_compare_1_25              : std_logic;
  SIGNAL switch_compare_1_26              : std_logic;
  SIGNAL switch_compare_1_27              : std_logic;
  SIGNAL switch_compare_1_28              : std_logic;
  SIGNAL switch_compare_1_29              : std_logic;
  SIGNAL switch_compare_1_30              : std_logic;
  SIGNAL switch_compare_1_31              : std_logic;
  SIGNAL Constant_out1                    : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Constant11_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL atan_out1                        : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay6_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Constant1_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add_add_cast                     : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add_add_cast_1                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add_add_temp                     : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add_out1                         : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract2_sub_cast               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract2_sub_cast_1             : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract2_sub_temp               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract2_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL atan_1_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay9_out1                 : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Constant2_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add3_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add3_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add3_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add3_out1                        : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract5_sub_cast               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract5_sub_cast_1             : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract5_sub_temp               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract5_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL atan_2_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay10_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Constant3_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add6_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add6_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add6_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add6_out1                        : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract8_sub_cast               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract8_sub_cast_1             : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract8_sub_temp               : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract8_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL atan_3_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay13_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Constant4_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add9_add_cast                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add9_add_cast_1                  : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add9_add_temp                    : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add9_out1                        : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract11_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract11_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract11_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract11_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL atan_4_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay16_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Constant5_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add12_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add12_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add12_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add12_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract14_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract14_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract14_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract14_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL atan_5_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay19_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Constant6_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add15_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add15_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add15_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add15_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract17_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract17_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract17_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract17_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL atan_6_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay22_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Constant7_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add18_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add18_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add18_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add18_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract20_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract20_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract20_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract20_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL atan_7_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay27_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Constant8_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add21_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add21_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add21_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add21_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract23_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract23_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract23_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract23_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL atan_8_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay28_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Constant9_out1                   : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add24_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add24_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add24_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add24_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract26_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract26_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract26_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract26_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL atan_9_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay31_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Constant10_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Add27_add_cast                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add27_add_cast_1                 : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add27_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Add27_out1                       : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Subtract29_sub_cast              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract29_sub_cast_1            : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract29_sub_temp              : signed(31 DOWNTO 0);  -- sfix32_En13
  SIGNAL Subtract29_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL atan_10_out1                     : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay34_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Switch_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay56_out1                : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Constant12_out1                  : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Switch1_out1                     : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Unit_Delay57_out1                : signed(15 DOWNTO 0);  -- sfix16_En13

BEGIN
  In1_signed <= signed(In1);

  enb <= clk_enable;

  Unit_Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay2_reg <= (OTHERS => to_signed(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay2_reg(0) <= In1_signed;
        Unit_Delay2_reg(1) <= Unit_Delay2_reg(0);
      END IF;
    END IF;
  END PROCESS Unit_Delay2_process;

  Unit_Delay2_out1 <= Unit_Delay2_reg(1);

  
  Compare_To_Zero_out1 <= '1' WHEN Unit_Delay2_out1 = to_signed(16#0000#, 16) ELSE
      '0';

  In2_signed <= signed(In2);

  Unit_Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay3_reg <= (OTHERS => to_signed(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay3_reg(0) <= In2_signed;
        Unit_Delay3_reg(1) <= Unit_Delay3_reg(0);
      END IF;
    END IF;
  END PROCESS Unit_Delay3_process;

  Unit_Delay3_out1 <= Unit_Delay3_reg(1);

  
  Compare_To_Zero1_out1 <= '1' WHEN Unit_Delay3_out1 = to_signed(16#0000#, 16) ELSE
      '0';

  Logical_Operator_out1 <= Compare_To_Zero_out1 AND Compare_To_Zero1_out1;

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay2_reg(0) <= Logical_Operator_out1;
        Delay2_reg(1 TO 11) <= Delay2_reg(0 TO 10);
      END IF;
    END IF;
  END PROCESS Delay2_process;

  Delay2_out1 <= Delay2_reg(11);

  
  switch_compare_1 <= '1' WHEN Delay2_out1 = '1' ELSE
      '0';

  
  Compare_To_Zero2_out1 <= '1' WHEN Unit_Delay2_out1 = to_signed(16#0000#, 16) ELSE
      '0';

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_reg(0) <= Compare_To_Zero2_out1;
        Delay1_reg(1 TO 10) <= Delay1_reg(0 TO 9);
      END IF;
    END IF;
  END PROCESS Delay1_process;

  Delay1_out1 <= Delay1_reg(10);

  
  switch_compare_1_1 <= '1' WHEN Delay1_out1 = '1' ELSE
      '0';

  
  Compare_To_Zero3_out1 <= '1' WHEN Unit_Delay3_out1 < to_signed(16#0000#, 16) ELSE
      '0';

  
  switch_compare_1_2 <= '1' WHEN Compare_To_Zero3_out1 > '0' ELSE
      '0';

  Constant15_out1 <= to_signed(16#0000#, 16);

  minusina_sub_cast <= resize(Constant15_out1, 32);
  minusina_sub_cast_1 <= resize(Unit_Delay2_out1, 32);
  minusina_sub_temp <= minusina_sub_cast - minusina_sub_cast_1;
  minusina_out1 <= minusina_sub_temp(15 DOWNTO 0);

  plusina_sub_cast <= resize(Unit_Delay2_out1, 32);
  plusina_sub_cast_1 <= resize(Constant15_out1, 32);
  plusina_sub_temp <= plusina_sub_cast - plusina_sub_cast_1;
  plusina_out1 <= plusina_sub_temp(15 DOWNTO 0);

  
  tempB_out1 <= minusina_out1 WHEN switch_compare_1_2 = '0' ELSE
      plusina_out1;

  Unit_Delay5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay5_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay5_out1 <= tempB_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay5_process;


  Constant23_out1 <= to_signed(16#0000#, 16);

  
  Relational_Operator1_relop1 <= '1' WHEN Unit_Delay5_out1 < Constant23_out1 ELSE
      '0';

  
  switch_compare_1_3 <= '1' WHEN Relational_Operator1_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_4 <= '1' WHEN Compare_To_Zero3_out1 > '0' ELSE
      '0';

  plusinb_sub_cast <= resize(Unit_Delay3_out1, 32);
  plusinb_sub_cast_1 <= resize(Constant15_out1, 32);
  plusinb_sub_temp <= plusinb_sub_cast - plusinb_sub_cast_1;
  plusinb_out1 <= plusinb_sub_temp(15 DOWNTO 0);

  minusinb_sub_cast <= resize(Constant15_out1, 32);
  minusinb_sub_cast_1 <= resize(Unit_Delay3_out1, 32);
  minusinb_sub_temp <= minusinb_sub_cast - minusinb_sub_cast_1;
  minusinb_out1 <= minusinb_sub_temp(15 DOWNTO 0);

  
  tempA_out1 <= plusinb_out1 WHEN switch_compare_1_4 = '0' ELSE
      minusinb_out1;

  Unit_Delay4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay4_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay4_out1 <= tempA_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay4_process;


  Subtract3_sub_cast <= resize(Unit_Delay5_out1, 32);
  Subtract3_sub_cast_1 <= resize(Unit_Delay4_out1, 32);
  Subtract3_sub_temp <= Subtract3_sub_cast - Subtract3_sub_cast_1;
  Subtract3_out1 <= Subtract3_sub_temp(15 DOWNTO 0);

  Add1_add_cast <= resize(Unit_Delay5_out1, 32);
  Add1_add_cast_1 <= resize(Unit_Delay4_out1, 32);
  Add1_add_temp <= Add1_add_cast + Add1_add_cast_1;
  Add1_out1 <= Add1_add_temp(15 DOWNTO 0);

  
  tempB1_out1 <= Subtract3_out1 WHEN switch_compare_1_3 = '0' ELSE
      Add1_out1;

  Unit_Delay8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay8_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay8_out1 <= tempB1_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay8_process;


  
  Relational_Operator2_relop1 <= '1' WHEN Unit_Delay8_out1 < Constant23_out1 ELSE
      '0';

  
  switch_compare_1_5 <= '1' WHEN Relational_Operator2_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_6 <= '1' WHEN Relational_Operator1_relop1 > '0' ELSE
      '0';

  Add2_add_cast <= resize(Unit_Delay4_out1, 32);
  Add2_add_cast_1 <= resize(Unit_Delay5_out1, 32);
  Add2_add_temp <= Add2_add_cast + Add2_add_cast_1;
  Add2_out1 <= Add2_add_temp(15 DOWNTO 0);

  Subtract4_sub_cast <= resize(Unit_Delay4_out1, 32);
  Subtract4_sub_cast_1 <= resize(Unit_Delay5_out1, 32);
  Subtract4_sub_temp <= Subtract4_sub_cast - Subtract4_sub_cast_1;
  Subtract4_out1 <= Subtract4_sub_temp(15 DOWNTO 0);

  
  tempA1_out1 <= Add2_out1 WHEN switch_compare_1_6 = '0' ELSE
      Subtract4_out1;

  Unit_Delay7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay7_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay7_out1 <= tempA1_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay7_process;


  Bit_Shift2_out1 <= SHIFT_RIGHT(Unit_Delay7_out1, 1);

  Subtract6_sub_cast <= resize(Unit_Delay8_out1, 32);
  Subtract6_sub_cast_1 <= resize(Bit_Shift2_out1, 32);
  Subtract6_sub_temp <= Subtract6_sub_cast - Subtract6_sub_cast_1;
  Subtract6_out1 <= Subtract6_sub_temp(15 DOWNTO 0);

  Add4_add_cast <= resize(Unit_Delay8_out1, 32);
  Add4_add_cast_1 <= resize(Bit_Shift2_out1, 32);
  Add4_add_temp <= Add4_add_cast + Add4_add_cast_1;
  Add4_out1 <= Add4_add_temp(15 DOWNTO 0);

  
  tempB2_out1 <= Subtract6_out1 WHEN switch_compare_1_5 = '0' ELSE
      Add4_out1;

  Unit_Delay11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay11_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay11_out1 <= tempB2_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay11_process;


  
  Relational_Operator3_relop1 <= '1' WHEN Unit_Delay11_out1 < Constant23_out1 ELSE
      '0';

  
  switch_compare_1_7 <= '1' WHEN Relational_Operator3_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_8 <= '1' WHEN Relational_Operator2_relop1 > '0' ELSE
      '0';

  Bit_Shift3_out1 <= SHIFT_RIGHT(Unit_Delay8_out1, 1);

  Add5_add_cast <= resize(Unit_Delay7_out1, 32);
  Add5_add_cast_1 <= resize(Bit_Shift3_out1, 32);
  Add5_add_temp <= Add5_add_cast + Add5_add_cast_1;
  Add5_out1 <= Add5_add_temp(15 DOWNTO 0);

  Subtract7_sub_cast <= resize(Unit_Delay7_out1, 32);
  Subtract7_sub_cast_1 <= resize(Bit_Shift3_out1, 32);
  Subtract7_sub_temp <= Subtract7_sub_cast - Subtract7_sub_cast_1;
  Subtract7_out1 <= Subtract7_sub_temp(15 DOWNTO 0);

  
  tempA2_out1 <= Add5_out1 WHEN switch_compare_1_8 = '0' ELSE
      Subtract7_out1;

  Unit_Delay12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay12_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay12_out1 <= tempA2_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay12_process;


  Bit_Shift4_out1 <= SHIFT_RIGHT(Unit_Delay12_out1, 2);

  Subtract9_sub_cast <= resize(Unit_Delay11_out1, 32);
  Subtract9_sub_cast_1 <= resize(Bit_Shift4_out1, 32);
  Subtract9_sub_temp <= Subtract9_sub_cast - Subtract9_sub_cast_1;
  Subtract9_out1 <= Subtract9_sub_temp(15 DOWNTO 0);

  Add7_add_cast <= resize(Unit_Delay11_out1, 32);
  Add7_add_cast_1 <= resize(Bit_Shift4_out1, 32);
  Add7_add_temp <= Add7_add_cast + Add7_add_cast_1;
  Add7_out1 <= Add7_add_temp(15 DOWNTO 0);

  
  tempB3_out1 <= Subtract9_out1 WHEN switch_compare_1_7 = '0' ELSE
      Add7_out1;

  Unit_Delay14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay14_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay14_out1 <= tempB3_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay14_process;


  
  Relational_Operator4_relop1 <= '1' WHEN Unit_Delay14_out1 < Constant23_out1 ELSE
      '0';

  
  switch_compare_1_9 <= '1' WHEN Relational_Operator4_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_10 <= '1' WHEN Relational_Operator3_relop1 > '0' ELSE
      '0';

  Bit_Shift5_out1 <= SHIFT_RIGHT(Unit_Delay11_out1, 2);

  Add8_add_cast <= resize(Unit_Delay12_out1, 32);
  Add8_add_cast_1 <= resize(Bit_Shift5_out1, 32);
  Add8_add_temp <= Add8_add_cast + Add8_add_cast_1;
  Add8_out1 <= Add8_add_temp(15 DOWNTO 0);

  Subtract10_sub_cast <= resize(Unit_Delay12_out1, 32);
  Subtract10_sub_cast_1 <= resize(Bit_Shift5_out1, 32);
  Subtract10_sub_temp <= Subtract10_sub_cast - Subtract10_sub_cast_1;
  Subtract10_out1 <= Subtract10_sub_temp(15 DOWNTO 0);

  
  tempA3_out1 <= Add8_out1 WHEN switch_compare_1_10 = '0' ELSE
      Subtract10_out1;

  Unit_Delay15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay15_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay15_out1 <= tempA3_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay15_process;


  Bit_Shift6_out1 <= SHIFT_RIGHT(Unit_Delay15_out1, 3);

  Subtract12_sub_cast <= resize(Unit_Delay14_out1, 32);
  Subtract12_sub_cast_1 <= resize(Bit_Shift6_out1, 32);
  Subtract12_sub_temp <= Subtract12_sub_cast - Subtract12_sub_cast_1;
  Subtract12_out1 <= Subtract12_sub_temp(15 DOWNTO 0);

  Add10_add_cast <= resize(Unit_Delay14_out1, 32);
  Add10_add_cast_1 <= resize(Bit_Shift6_out1, 32);
  Add10_add_temp <= Add10_add_cast + Add10_add_cast_1;
  Add10_out1 <= Add10_add_temp(15 DOWNTO 0);

  
  tempB4_out1 <= Subtract12_out1 WHEN switch_compare_1_9 = '0' ELSE
      Add10_out1;

  Unit_Delay17_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay17_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay17_out1 <= tempB4_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay17_process;


  
  Relational_Operator5_relop1 <= '1' WHEN Unit_Delay17_out1 < Constant23_out1 ELSE
      '0';

  
  switch_compare_1_11 <= '1' WHEN Relational_Operator5_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_12 <= '1' WHEN Relational_Operator4_relop1 > '0' ELSE
      '0';

  Bit_Shift7_out1 <= SHIFT_RIGHT(Unit_Delay14_out1, 3);

  Add11_add_cast <= resize(Unit_Delay15_out1, 32);
  Add11_add_cast_1 <= resize(Bit_Shift7_out1, 32);
  Add11_add_temp <= Add11_add_cast + Add11_add_cast_1;
  Add11_out1 <= Add11_add_temp(15 DOWNTO 0);

  Subtract13_sub_cast <= resize(Unit_Delay15_out1, 32);
  Subtract13_sub_cast_1 <= resize(Bit_Shift7_out1, 32);
  Subtract13_sub_temp <= Subtract13_sub_cast - Subtract13_sub_cast_1;
  Subtract13_out1 <= Subtract13_sub_temp(15 DOWNTO 0);

  
  tempA4_out1 <= Add11_out1 WHEN switch_compare_1_12 = '0' ELSE
      Subtract13_out1;

  Unit_Delay18_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay18_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay18_out1 <= tempA4_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay18_process;


  Bit_Shift8_out1 <= SHIFT_RIGHT(Unit_Delay18_out1, 4);

  Subtract15_sub_cast <= resize(Unit_Delay17_out1, 32);
  Subtract15_sub_cast_1 <= resize(Bit_Shift8_out1, 32);
  Subtract15_sub_temp <= Subtract15_sub_cast - Subtract15_sub_cast_1;
  Subtract15_out1 <= Subtract15_sub_temp(15 DOWNTO 0);

  Add13_add_cast <= resize(Unit_Delay17_out1, 32);
  Add13_add_cast_1 <= resize(Bit_Shift8_out1, 32);
  Add13_add_temp <= Add13_add_cast + Add13_add_cast_1;
  Add13_out1 <= Add13_add_temp(15 DOWNTO 0);

  
  tempB5_out1 <= Subtract15_out1 WHEN switch_compare_1_11 = '0' ELSE
      Add13_out1;

  Unit_Delay20_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay20_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay20_out1 <= tempB5_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay20_process;


  
  Relational_Operator6_relop1 <= '1' WHEN Unit_Delay20_out1 < Constant23_out1 ELSE
      '0';

  
  switch_compare_1_13 <= '1' WHEN Relational_Operator6_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_14 <= '1' WHEN Relational_Operator5_relop1 > '0' ELSE
      '0';

  Bit_Shift9_out1 <= SHIFT_RIGHT(Unit_Delay17_out1, 4);

  Add14_add_cast <= resize(Unit_Delay18_out1, 32);
  Add14_add_cast_1 <= resize(Bit_Shift9_out1, 32);
  Add14_add_temp <= Add14_add_cast + Add14_add_cast_1;
  Add14_out1 <= Add14_add_temp(15 DOWNTO 0);

  Subtract16_sub_cast <= resize(Unit_Delay18_out1, 32);
  Subtract16_sub_cast_1 <= resize(Bit_Shift9_out1, 32);
  Subtract16_sub_temp <= Subtract16_sub_cast - Subtract16_sub_cast_1;
  Subtract16_out1 <= Subtract16_sub_temp(15 DOWNTO 0);

  
  tempA5_out1 <= Add14_out1 WHEN switch_compare_1_14 = '0' ELSE
      Subtract16_out1;

  Unit_Delay21_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay21_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay21_out1 <= tempA5_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay21_process;


  Bit_Shift10_out1 <= SHIFT_RIGHT(Unit_Delay21_out1, 5);

  Subtract18_sub_cast <= resize(Unit_Delay20_out1, 32);
  Subtract18_sub_cast_1 <= resize(Bit_Shift10_out1, 32);
  Subtract18_sub_temp <= Subtract18_sub_cast - Subtract18_sub_cast_1;
  Subtract18_out1 <= Subtract18_sub_temp(15 DOWNTO 0);

  Add16_add_cast <= resize(Unit_Delay20_out1, 32);
  Add16_add_cast_1 <= resize(Bit_Shift10_out1, 32);
  Add16_add_temp <= Add16_add_cast + Add16_add_cast_1;
  Add16_out1 <= Add16_add_temp(15 DOWNTO 0);

  
  tempB6_out1 <= Subtract18_out1 WHEN switch_compare_1_13 = '0' ELSE
      Add16_out1;

  Unit_Delay23_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay23_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay23_out1 <= tempB6_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay23_process;


  
  Relational_Operator7_relop1 <= '1' WHEN Unit_Delay23_out1 < Constant23_out1 ELSE
      '0';

  
  switch_compare_1_15 <= '1' WHEN Relational_Operator7_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_16 <= '1' WHEN Relational_Operator6_relop1 > '0' ELSE
      '0';

  Bit_Shift11_out1 <= SHIFT_RIGHT(Unit_Delay20_out1, 5);

  Add17_add_cast <= resize(Unit_Delay21_out1, 32);
  Add17_add_cast_1 <= resize(Bit_Shift11_out1, 32);
  Add17_add_temp <= Add17_add_cast + Add17_add_cast_1;
  Add17_out1 <= Add17_add_temp(15 DOWNTO 0);

  Subtract19_sub_cast <= resize(Unit_Delay21_out1, 32);
  Subtract19_sub_cast_1 <= resize(Bit_Shift11_out1, 32);
  Subtract19_sub_temp <= Subtract19_sub_cast - Subtract19_sub_cast_1;
  Subtract19_out1 <= Subtract19_sub_temp(15 DOWNTO 0);

  
  tempA6_out1 <= Add17_out1 WHEN switch_compare_1_16 = '0' ELSE
      Subtract19_out1;

  Unit_Delay24_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay24_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay24_out1 <= tempA6_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay24_process;


  Bit_Shift12_out1 <= SHIFT_RIGHT(Unit_Delay24_out1, 6);

  Subtract21_sub_cast <= resize(Unit_Delay23_out1, 32);
  Subtract21_sub_cast_1 <= resize(Bit_Shift12_out1, 32);
  Subtract21_sub_temp <= Subtract21_sub_cast - Subtract21_sub_cast_1;
  Subtract21_out1 <= Subtract21_sub_temp(15 DOWNTO 0);

  Add19_add_cast <= resize(Unit_Delay23_out1, 32);
  Add19_add_cast_1 <= resize(Bit_Shift12_out1, 32);
  Add19_add_temp <= Add19_add_cast + Add19_add_cast_1;
  Add19_out1 <= Add19_add_temp(15 DOWNTO 0);

  
  tempB7_out1 <= Subtract21_out1 WHEN switch_compare_1_15 = '0' ELSE
      Add19_out1;

  Unit_Delay26_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay26_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay26_out1 <= tempB7_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay26_process;


  
  Relational_Operator8_relop1 <= '1' WHEN Unit_Delay26_out1 < Constant23_out1 ELSE
      '0';

  
  switch_compare_1_17 <= '1' WHEN Relational_Operator8_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_18 <= '1' WHEN Relational_Operator7_relop1 > '0' ELSE
      '0';

  Bit_Shift13_out1 <= SHIFT_RIGHT(Unit_Delay23_out1, 6);

  Add20_add_cast <= resize(Unit_Delay24_out1, 32);
  Add20_add_cast_1 <= resize(Bit_Shift13_out1, 32);
  Add20_add_temp <= Add20_add_cast + Add20_add_cast_1;
  Add20_out1 <= Add20_add_temp(15 DOWNTO 0);

  Subtract22_sub_cast <= resize(Unit_Delay24_out1, 32);
  Subtract22_sub_cast_1 <= resize(Bit_Shift13_out1, 32);
  Subtract22_sub_temp <= Subtract22_sub_cast - Subtract22_sub_cast_1;
  Subtract22_out1 <= Subtract22_sub_temp(15 DOWNTO 0);

  
  tempA7_out1 <= Add20_out1 WHEN switch_compare_1_18 = '0' ELSE
      Subtract22_out1;

  Unit_Delay25_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay25_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay25_out1 <= tempA7_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay25_process;


  Bit_Shift14_out1 <= SHIFT_RIGHT(Unit_Delay25_out1, 7);

  Subtract24_sub_cast <= resize(Unit_Delay26_out1, 32);
  Subtract24_sub_cast_1 <= resize(Bit_Shift14_out1, 32);
  Subtract24_sub_temp <= Subtract24_sub_cast - Subtract24_sub_cast_1;
  Subtract24_out1 <= Subtract24_sub_temp(15 DOWNTO 0);

  Add22_add_cast <= resize(Unit_Delay26_out1, 32);
  Add22_add_cast_1 <= resize(Bit_Shift14_out1, 32);
  Add22_add_temp <= Add22_add_cast + Add22_add_cast_1;
  Add22_out1 <= Add22_add_temp(15 DOWNTO 0);

  
  tempB8_out1 <= Subtract24_out1 WHEN switch_compare_1_17 = '0' ELSE
      Add22_out1;

  Unit_Delay29_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay29_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay29_out1 <= tempB8_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay29_process;


  
  Relational_Operator9_relop1 <= '1' WHEN Unit_Delay29_out1 < Constant23_out1 ELSE
      '0';

  
  switch_compare_1_19 <= '1' WHEN Relational_Operator9_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_20 <= '1' WHEN Relational_Operator8_relop1 > '0' ELSE
      '0';

  Bit_Shift15_out1 <= SHIFT_RIGHT(Unit_Delay26_out1, 7);

  Add23_add_cast <= resize(Unit_Delay25_out1, 32);
  Add23_add_cast_1 <= resize(Bit_Shift15_out1, 32);
  Add23_add_temp <= Add23_add_cast + Add23_add_cast_1;
  Add23_out1 <= Add23_add_temp(15 DOWNTO 0);

  Subtract25_sub_cast <= resize(Unit_Delay25_out1, 32);
  Subtract25_sub_cast_1 <= resize(Bit_Shift15_out1, 32);
  Subtract25_sub_temp <= Subtract25_sub_cast - Subtract25_sub_cast_1;
  Subtract25_out1 <= Subtract25_sub_temp(15 DOWNTO 0);

  
  tempA8_out1 <= Add23_out1 WHEN switch_compare_1_20 = '0' ELSE
      Subtract25_out1;

  Unit_Delay30_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay30_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay30_out1 <= tempA8_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay30_process;


  Bit_Shift16_out1 <= SHIFT_RIGHT(Unit_Delay30_out1, 8);

  Subtract27_sub_cast <= resize(Unit_Delay29_out1, 32);
  Subtract27_sub_cast_1 <= resize(Bit_Shift16_out1, 32);
  Subtract27_sub_temp <= Subtract27_sub_cast - Subtract27_sub_cast_1;
  Subtract27_out1 <= Subtract27_sub_temp(15 DOWNTO 0);

  Add25_add_cast <= resize(Unit_Delay29_out1, 32);
  Add25_add_cast_1 <= resize(Bit_Shift16_out1, 32);
  Add25_add_temp <= Add25_add_cast + Add25_add_cast_1;
  Add25_out1 <= Add25_add_temp(15 DOWNTO 0);

  
  tempB9_out1 <= Subtract27_out1 WHEN switch_compare_1_19 = '0' ELSE
      Add25_out1;

  Unit_Delay32_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay32_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay32_out1 <= tempB9_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay32_process;


  
  Relational_Operator10_relop1 <= '1' WHEN Unit_Delay32_out1 < Constant23_out1 ELSE
      '0';

  
  switch_compare_1_21 <= '1' WHEN Relational_Operator10_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_22 <= '1' WHEN Relational_Operator9_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_23 <= '1' WHEN Relational_Operator8_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_24 <= '1' WHEN Relational_Operator7_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_25 <= '1' WHEN Relational_Operator6_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_26 <= '1' WHEN Relational_Operator5_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_27 <= '1' WHEN Relational_Operator4_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_28 <= '1' WHEN Relational_Operator3_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_29 <= '1' WHEN Relational_Operator2_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_30 <= '1' WHEN Relational_Operator1_relop1 > '0' ELSE
      '0';

  
  switch_compare_1_31 <= '1' WHEN Compare_To_Zero3_out1 > '0' ELSE
      '0';

  Constant_out1 <= to_signed(16#3244#, 16);

  Constant11_out1 <= to_signed(-16#3244#, 16);

  
  atan_out1 <= Constant_out1 WHEN switch_compare_1_31 = '0' ELSE
      Constant11_out1;

  Unit_Delay6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay6_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay6_out1 <= atan_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay6_process;


  Constant1_out1 <= to_signed(16#1922#, 16);

  Add_add_cast <= resize(Unit_Delay6_out1, 32);
  Add_add_cast_1 <= resize(Constant1_out1, 32);
  Add_add_temp <= Add_add_cast + Add_add_cast_1;
  Add_out1 <= Add_add_temp(15 DOWNTO 0);

  Subtract2_sub_cast <= resize(Unit_Delay6_out1, 32);
  Subtract2_sub_cast_1 <= resize(Constant1_out1, 32);
  Subtract2_sub_temp <= Subtract2_sub_cast - Subtract2_sub_cast_1;
  Subtract2_out1 <= Subtract2_sub_temp(15 DOWNTO 0);

  
  atan_1_out1 <= Add_out1 WHEN switch_compare_1_30 = '0' ELSE
      Subtract2_out1;

  Unit_Delay9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay9_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay9_out1 <= atan_1_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay9_process;


  Constant2_out1 <= to_signed(16#0ED6#, 16);

  Add3_add_cast <= resize(Unit_Delay9_out1, 32);
  Add3_add_cast_1 <= resize(Constant2_out1, 32);
  Add3_add_temp <= Add3_add_cast + Add3_add_cast_1;
  Add3_out1 <= Add3_add_temp(15 DOWNTO 0);

  Subtract5_sub_cast <= resize(Unit_Delay9_out1, 32);
  Subtract5_sub_cast_1 <= resize(Constant2_out1, 32);
  Subtract5_sub_temp <= Subtract5_sub_cast - Subtract5_sub_cast_1;
  Subtract5_out1 <= Subtract5_sub_temp(15 DOWNTO 0);

  
  atan_2_out1 <= Add3_out1 WHEN switch_compare_1_29 = '0' ELSE
      Subtract5_out1;

  Unit_Delay10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay10_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay10_out1 <= atan_2_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay10_process;


  Constant3_out1 <= to_signed(16#07D7#, 16);

  Add6_add_cast <= resize(Unit_Delay10_out1, 32);
  Add6_add_cast_1 <= resize(Constant3_out1, 32);
  Add6_add_temp <= Add6_add_cast + Add6_add_cast_1;
  Add6_out1 <= Add6_add_temp(15 DOWNTO 0);

  Subtract8_sub_cast <= resize(Unit_Delay10_out1, 32);
  Subtract8_sub_cast_1 <= resize(Constant3_out1, 32);
  Subtract8_sub_temp <= Subtract8_sub_cast - Subtract8_sub_cast_1;
  Subtract8_out1 <= Subtract8_sub_temp(15 DOWNTO 0);

  
  atan_3_out1 <= Add6_out1 WHEN switch_compare_1_28 = '0' ELSE
      Subtract8_out1;

  Unit_Delay13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay13_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay13_out1 <= atan_3_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay13_process;


  Constant4_out1 <= to_signed(16#03FB#, 16);

  Add9_add_cast <= resize(Unit_Delay13_out1, 32);
  Add9_add_cast_1 <= resize(Constant4_out1, 32);
  Add9_add_temp <= Add9_add_cast + Add9_add_cast_1;
  Add9_out1 <= Add9_add_temp(15 DOWNTO 0);

  Subtract11_sub_cast <= resize(Unit_Delay13_out1, 32);
  Subtract11_sub_cast_1 <= resize(Constant4_out1, 32);
  Subtract11_sub_temp <= Subtract11_sub_cast - Subtract11_sub_cast_1;
  Subtract11_out1 <= Subtract11_sub_temp(15 DOWNTO 0);

  
  atan_4_out1 <= Add9_out1 WHEN switch_compare_1_27 = '0' ELSE
      Subtract11_out1;

  Unit_Delay16_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay16_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay16_out1 <= atan_4_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay16_process;


  Constant5_out1 <= to_signed(16#01FF#, 16);

  Add12_add_cast <= resize(Unit_Delay16_out1, 32);
  Add12_add_cast_1 <= resize(Constant5_out1, 32);
  Add12_add_temp <= Add12_add_cast + Add12_add_cast_1;
  Add12_out1 <= Add12_add_temp(15 DOWNTO 0);

  Subtract14_sub_cast <= resize(Unit_Delay16_out1, 32);
  Subtract14_sub_cast_1 <= resize(Constant5_out1, 32);
  Subtract14_sub_temp <= Subtract14_sub_cast - Subtract14_sub_cast_1;
  Subtract14_out1 <= Subtract14_sub_temp(15 DOWNTO 0);

  
  atan_5_out1 <= Add12_out1 WHEN switch_compare_1_26 = '0' ELSE
      Subtract14_out1;

  Unit_Delay19_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay19_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay19_out1 <= atan_5_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay19_process;


  Constant6_out1 <= to_signed(16#0100#, 16);

  Add15_add_cast <= resize(Unit_Delay19_out1, 32);
  Add15_add_cast_1 <= resize(Constant6_out1, 32);
  Add15_add_temp <= Add15_add_cast + Add15_add_cast_1;
  Add15_out1 <= Add15_add_temp(15 DOWNTO 0);

  Subtract17_sub_cast <= resize(Unit_Delay19_out1, 32);
  Subtract17_sub_cast_1 <= resize(Constant6_out1, 32);
  Subtract17_sub_temp <= Subtract17_sub_cast - Subtract17_sub_cast_1;
  Subtract17_out1 <= Subtract17_sub_temp(15 DOWNTO 0);

  
  atan_6_out1 <= Add15_out1 WHEN switch_compare_1_25 = '0' ELSE
      Subtract17_out1;

  Unit_Delay22_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay22_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay22_out1 <= atan_6_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay22_process;


  Constant7_out1 <= to_signed(16#0080#, 16);

  Add18_add_cast <= resize(Unit_Delay22_out1, 32);
  Add18_add_cast_1 <= resize(Constant7_out1, 32);
  Add18_add_temp <= Add18_add_cast + Add18_add_cast_1;
  Add18_out1 <= Add18_add_temp(15 DOWNTO 0);

  Subtract20_sub_cast <= resize(Unit_Delay22_out1, 32);
  Subtract20_sub_cast_1 <= resize(Constant7_out1, 32);
  Subtract20_sub_temp <= Subtract20_sub_cast - Subtract20_sub_cast_1;
  Subtract20_out1 <= Subtract20_sub_temp(15 DOWNTO 0);

  
  atan_7_out1 <= Add18_out1 WHEN switch_compare_1_24 = '0' ELSE
      Subtract20_out1;

  Unit_Delay27_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay27_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay27_out1 <= atan_7_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay27_process;


  Constant8_out1 <= to_signed(16#0040#, 16);

  Add21_add_cast <= resize(Unit_Delay27_out1, 32);
  Add21_add_cast_1 <= resize(Constant8_out1, 32);
  Add21_add_temp <= Add21_add_cast + Add21_add_cast_1;
  Add21_out1 <= Add21_add_temp(15 DOWNTO 0);

  Subtract23_sub_cast <= resize(Unit_Delay27_out1, 32);
  Subtract23_sub_cast_1 <= resize(Constant8_out1, 32);
  Subtract23_sub_temp <= Subtract23_sub_cast - Subtract23_sub_cast_1;
  Subtract23_out1 <= Subtract23_sub_temp(15 DOWNTO 0);

  
  atan_8_out1 <= Add21_out1 WHEN switch_compare_1_23 = '0' ELSE
      Subtract23_out1;

  Unit_Delay28_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay28_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay28_out1 <= atan_8_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay28_process;


  Constant9_out1 <= to_signed(16#0020#, 16);

  Add24_add_cast <= resize(Unit_Delay28_out1, 32);
  Add24_add_cast_1 <= resize(Constant9_out1, 32);
  Add24_add_temp <= Add24_add_cast + Add24_add_cast_1;
  Add24_out1 <= Add24_add_temp(15 DOWNTO 0);

  Subtract26_sub_cast <= resize(Unit_Delay28_out1, 32);
  Subtract26_sub_cast_1 <= resize(Constant9_out1, 32);
  Subtract26_sub_temp <= Subtract26_sub_cast - Subtract26_sub_cast_1;
  Subtract26_out1 <= Subtract26_sub_temp(15 DOWNTO 0);

  
  atan_9_out1 <= Add24_out1 WHEN switch_compare_1_22 = '0' ELSE
      Subtract26_out1;

  Unit_Delay31_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay31_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay31_out1 <= atan_9_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay31_process;


  Constant10_out1 <= to_signed(16#0010#, 16);

  Add27_add_cast <= resize(Unit_Delay31_out1, 32);
  Add27_add_cast_1 <= resize(Constant10_out1, 32);
  Add27_add_temp <= Add27_add_cast + Add27_add_cast_1;
  Add27_out1 <= Add27_add_temp(15 DOWNTO 0);

  Subtract29_sub_cast <= resize(Unit_Delay31_out1, 32);
  Subtract29_sub_cast_1 <= resize(Constant10_out1, 32);
  Subtract29_sub_temp <= Subtract29_sub_cast - Subtract29_sub_cast_1;
  Subtract29_out1 <= Subtract29_sub_temp(15 DOWNTO 0);

  
  atan_10_out1 <= Add27_out1 WHEN switch_compare_1_21 = '0' ELSE
      Subtract29_out1;

  Unit_Delay34_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay34_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay34_out1 <= atan_10_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay34_process;


  
  Switch_out1 <= Unit_Delay34_out1 WHEN switch_compare_1_1 = '0' ELSE
      Unit_Delay6_out1;

  Unit_Delay56_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay56_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay56_out1 <= Switch_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay56_process;


  Constant12_out1 <= to_signed(16#0000#, 16);

  
  Switch1_out1 <= Unit_Delay56_out1 WHEN switch_compare_1 = '0' ELSE
      Constant12_out1;

  Unit_Delay57_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay57_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay57_out1 <= Switch1_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay57_process;


  Out1 <= std_logic_vector(Unit_Delay57_out1);

  ce_out <= clk_enable;



END rtl;

